In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
%matplotlib inline
# Adjusting column and row numbers to be shown
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)
import feather

In [2]:
KT1= pd.read_feather('KT1new.ftr')
#KT2= pd.read_feather('KT2.ftr')
#KT3= pd.read_feather('KT3.ftr')
KT4= pd.read_feather('KT4.ftr')

In [3]:
questions= pd.read_csv('questions.csv')
lectures= pd.read_csv('lectures.csv')

In [4]:
KT1.head()

timestamp  solving_id question_id user_answer  elapsed_time
0  1565096190868           1       q5012           b         38000
1  1565096221062           2       q4706           c         24000
2  1565096293432           3       q4366           b         68000
3  1565096339668           4       q4829           a         42000
4  1565096401774           5       q6528           b         59000

In [5]:
KT4.head()

timestamp action_type item_id  cursor_time     source user_answer  \
0  1565096151269       enter   b3544          NaN  diagnosis        None   
1  1565096187972     respond   q5012          NaN  diagnosis           b   
2  1565096194904      submit   b3544          NaN  diagnosis        None   
3  1565096195001       enter   b3238          NaN  diagnosis        None   
4  1565096218682     respond   q4706          NaN  diagnosis           c   

  platform  user_iD  
0   mobile        1  
1   mobile        1  
2   mobile        1  
3   mobile        1  
4   mobile        1

In [20]:
KT4['user_iD'].unique()

array([   1,   10,  100, ..., 9994, 9995, 9998])

In [27]:
KT4['user_iD'].isnull()

In [25]:
KT4.count()

timestamp      131375195
action_type    131375195
item_id        131375195
cursor_time     37268568
source         131347262
user_answer     28222286
platform       131347262
user_iD        131375195
dtype: int64

In [6]:
questions.head()

question_id bundle_id explanation_id correct_answer  part          tags  \
0          q1        b1             e1              b     1   1;2;179;181   
1          q2        b2             e2              a     1      15;2;182   
2          q3        b3             e3              b     1  14;2;179;183   
3          q4        b4             e4              b     1   9;2;179;184   
4          q5        b5             e5              c     1   8;2;179;181   

     deployed_at  
0  1558093217098  
1  1558093219720  
2  1558093222784  
3  1558093225357  
4  1558093228439

In [7]:
lectures.head()

lecture_id  part  tags  video_length    deployed_at
0       l520     5   142            -1             -1
1       l592     6   142            -1             -1
2      l1259     1   222        359000  1570424729123
3      l1260     1   220        487000  1570424738105
4      l1261     1   221        441000  1570424743162

In [ ]:
df1a = KT1.set_index('solving_id')
df2a = KT4.set_index('item_id')
df2b = KT4.set_index('cursor_time')
df2c = KT4.set_index('source')
df2d = KT4.set_index('user_answer')
df3a = KT4.set_index('timestamp')
df3b = KT4.set_index('action_type')
df3c = KT4.set_index('platform')
df3d = KT4.set_index('user_iD')

In [5]:
KT1.columns

Index(['timestamp', 'solving_id', 'question_id', 'user_answer',
       'elapsed_time'],
      dtype='object')

In [6]:
KT4.columns

Index(['timestamp', 'action_type', 'item_id', 'cursor_time', 'source',
       'user_answer', 'platform', 'user_iD'],
      dtype='object')

In [7]:
EdNet=KT1.append(KT4)
KT1.shape, KT4.shape, EdNet.shape

((31288731, 5), (131375195, 8), (162663926, 11))

In [8]:
EdNet.columns

Index(['timestamp', 'solving_id', 'question_id', 'user_answer', 'elapsed_time',
       'action_type', 'item_id', 'cursor_time', 'source', 'platform',
       'user_iD'],
      dtype='object')

In [9]:
EdNet.head()

timestamp  solving_id question_id user_answer  elapsed_time  \
0  1565096190868         1.0       q5012           b       38000.0   
1  1565096221062         2.0       q4706           c       24000.0   
2  1565096293432         3.0       q4366           b       68000.0   
3  1565096339668         4.0       q4829           a       42000.0   
4  1565096401774         5.0       q6528           b       59000.0   

  action_type item_id  cursor_time source platform  user_iD  
0         NaN     NaN          NaN    NaN      NaN      NaN  
1         NaN     NaN          NaN    NaN      NaN      NaN  
2         NaN     NaN          NaN    NaN      NaN      NaN  
3         NaN     NaN          NaN    NaN      NaN      NaN  
4         NaN     NaN          NaN    NaN      NaN      NaN

In [10]:
EdNet['action_type'].unique()

array([nan, 'enter', 'respond', 'submit', 'play_video', 'pause_video',
       'quit', 'play_audio', 'pause_audio', 'pay', 'erase_choice',
       'undo_erase_choice', 'refund', 'enroll_coupon'], dtype=object)

In [11]:
EdNet['item_id'].unique()

array([nan, 'b3544', 'q5012', ..., 'q5107', 'e3639', 'c6'], dtype=object)

In [12]:
EdNet['cursor_time'].unique()

array([    nan,      0.,   4805., ..., 349044., 349545., 351570.])

In [13]:
EdNet['source'].unique()

array([nan, 'diagnosis', 'archive', 'sprint', 'review', 'my_note',
       'review_quiz', 'adaptive_offer', None, 'tutor'], dtype=object)

In [14]:
EdNet['platform'].unique()

array([nan, 'mobile', None, 'web'], dtype=object)

In [15]:
EdNet['user_iD'].unique()

array([      nan, 1.000e+00, 1.000e+01, ..., 9.994e+03, 9.995e+03,
       9.998e+03])

In [18]:
len(EdNet['user_iD'])

162663926