In [4]:
import pandas as pd
import numpy as np
import feather
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)
from datetime import datetime

### READING THE FILES

In [5]:
KT1 = pd.read_feather("C:/Users/user1/Desktop/Concatinate/KT1.ftr")
KT2 = pd.read_feather("C:/Users/user1/Desktop/Concatinate/KT2.ftr")
KT3 = pd.read_feather("C:/Users/user1/Desktop/Concatinate/EDNET_KT3.ftr")
KT4 = pd.read_feather("C:/Users/user1/Desktop/Concatinate/KT4.ftr")

In [6]:
coupons = pd.read_csv("C:/Users/user1/Desktop/Concatinate/coupons.csv")   
lectures = pd.read_csv("C:/Users/user1/Desktop/Concatinate/lectures.csv")
questions = pd.read_csv("C:/Users/user1/Desktop/Concatinate/questions.csv")
payments = pd.read_csv("C:/Users/user1/Desktop/Concatinate/payments.csv")

### CHECKING THE COLUMNS NAME IN EACH FILE

In [8]:
KT1.columns

Index(['timestamp', 'solving_id', 'question_id', 'user_answer', 'elapsed_time',
       'user_iD'],
      dtype='object')

In [9]:
KT2.columns

Index(['timestamp', 'action_type', 'item_id', 'source', 'user_answer',
       'platform', 'user_iD'],
      dtype='object')

In [10]:
KT3.columns

Index(['timestamp', 'action_type', 'item_id', 'source', 'user_answer',
       'platform', 'user_iD'],
      dtype='object')

In [11]:
KT4.columns

Index(['timestamp', 'action_type', 'item_id', 'cursor_time', 'source',
       'user_answer', 'platform', 'user_iD'],
      dtype='object')

In [21]:
coupons.columns

Index(['coupon_id', 'coupon_type', 'duration'], dtype='object')

In [22]:
lectures.columns

Index(['lecture_id', 'part', 'tags', 'video_length', 'deployed_at'], dtype='object')

In [23]:
questions.columns

Index(['question_id', 'bundle_id', 'explanation_id', 'correct_answer', 'part',
       'tags', 'deployed_at'],
      dtype='object')

In [24]:
payments.columns

Index(['payment_item_id', 'type', 'duaration', 'number_of_questions'], dtype='object')

# CHECKING THE UNIQUE VALUES FOR EACH DATASET COLUMNS

## AT FIRST , WE CHECK THE UNIQUE VALUES OF COMMON COLUMNS IN EACH DATASET FILE

## USER ANSWER COLUMN

In [12]:
KT1['user_answer'].unique()

array(['b', 'c', 'a', 'd', None], dtype=object)

In [13]:
pd.value_counts(KT1['user_answer'], dropna=False)

b      27044099
a      25948414
c      24960934
d      17312833
NaN       27646
Name: user_answer, dtype: int64

In [14]:
KT2['user_answer'].unique()

array([None, 'b', 'c', 'a', 'd'], dtype=object)

In [15]:
pd.value_counts(KT2['user_answer'], dropna=False)

NaN    32976122
b       6789798
a       6380790
c       6075325
d       4138567
Name: user_answer, dtype: int64

In [16]:
KT3['user_answer'].unique()

array([None, 'b', 'c', 'a', 'd'], dtype=object)

In [17]:
pd.value_counts(KT3['user_answer'], dropna=False)

NaN    65886174
b       6789798
a       6380790
c       6075325
d       4138567
Name: user_answer, dtype: int64

In [18]:
KT4['user_answer'].unique()

array([None, 'b', 'c', 'a', 'd'], dtype=object)

In [19]:
pd.value_counts(KT4['user_answer'], dropna=False)

NaN    103200432
b        8232269
a        7972379
c        7192663
d        4843795
Name: user_answer, dtype: int64

## USER_ID COLUMN

In [20]:
KT1['user_iD'].unique()

array([     0,      1,      2, ..., 784306, 784307, 784308], dtype=int64)

In [21]:
pd.value_counts(KT1['user_iD'], dropna=False)

299547    40157
57719     36725
782730    34379
148228    32517
387942    32489
          ...  
267767        1
93599         1
273764        1
608644        1
681484        1
Name: user_iD, Length: 784309, dtype: int64

In [22]:
KT2['user_iD'].unique()

array([     0,      1,      2, ..., 297441, 297442, 297443], dtype=int64)

In [23]:
pd.value_counts(KT2['user_iD'], dropna=False)

297219    101821
279327     64796
19528      53778
297364     53557
297420     46387
           ...  
207620         2
54777          2
124707         2
284579         2
180861         2
Name: user_iD, Length: 297444, dtype: int64

In [24]:
KT3['user_iD'].unique()

array([     0,      1,      2, ..., 297912, 297913, 297914], dtype=int64)

In [25]:
pd.value_counts(KT3['user_iD'], dropna=False)

297689    169817
279762     95884
297835     92145
95798      64307
297891     62941
           ...  
75788          2
13760          2
220330         2
105383         2
177372         2
Name: user_iD, Length: 297915, dtype: int64

In [26]:
KT4['user_iD'].unique()

array([     0,      1,      2, ..., 297912, 297913, 297914], dtype=int64)

In [27]:
pd.value_counts(KT4['user_iD'], dropna=False)

3223      203338
297689    192752
297756    167432
297835    163306
279762    158503
           ...  
5527           2
238043         2
244239         2
158015         2
122271         2
Name: user_iD, Length: 297915, dtype: int64

## TimeStamp COLUMN

In [28]:
KT1['timestamp'].unique()

array([1565096190868, 1565096221062, 1565096293432, ..., 1516056728149,
       1515886887475, 1515886920805], dtype=int64)

In [29]:
pd.value_counts(KT1['timestamp'], dropna=False)

1568776999733    36
1568776999730    35
1568776999709    34
1568776863500    30
1568774514518    29
                 ..
1532972572892     1
1560512368858     1
1571996426436     1
1512269537476     1
1557412552884     1
Name: timestamp, Length: 92249541, dtype: int64

In [30]:
KT2['timestamp'].unique()

array([1565096151269, 1565096187972, 1565096194904, ..., 1568964975390,
       1568964992921, 1568964996503], dtype=int64)

In [31]:
pd.value_counts(KT2['timestamp'], dropna=False)

1572166887662    136
1572166850794    136
1569204703388    131
1572166825415    129
1567044237974    121
                ... 
1573031466146      1
1550587751589      1
1565770547989      1
1572259730618      1
1564734056767      1
Name: timestamp, Length: 56224340, dtype: int64

In [32]:
KT3['timestamp'].unique()

array([1565096151269, 1565096187972, 1565096194904, ..., 1568964996503,
       1568964996572, 1568965006334], dtype=int64)

In [33]:
pd.value_counts(KT3['timestamp'], dropna=False)

1572166850794    136
1572166887662    136
1569204703388    131
1572166825415    129
1567044237974    121
                ... 
1562540277659      1
1563874062233      1
1558689910661      1
1568491997060      1
1568073253200      1
Name: timestamp, Length: 89044977, dtype: int64

In [34]:
KT4['timestamp'].unique()

array([1565096151269, 1565096187972, 1565096194904, ..., 1568964996503,
       1568964996572, 1568965006334], dtype=int64)

In [35]:
pd.value_counts(KT4['timestamp'], dropna=False)

1567330321794    394
1567330332052    386
1567330294349    372
1567330318430    369
1567330290835    349
                ... 
1573621657088      1
1572313271772      1
1557590026142      1
1562128258968      1
1541834903730      1
Name: timestamp, Length: 127329659, dtype: int64

# NOW THE COMMON COLUMNS BETWEEN KT2,KT3,KT4 ONLY

## Platform Column

In [37]:
KT2['platform'].unique()

array(['mobile', 'web'], dtype=object)

In [38]:
pd.value_counts(KT2['platform'], dropna=False)

mobile    39622254
web       16738348
Name: platform, dtype: int64

In [39]:
KT3['platform'].unique()

array(['mobile', 'web'], dtype=object)

In [40]:
pd.value_counts(KT3['platform'], dropna=False)

mobile    63514718
web       25755936
Name: platform, dtype: int64

In [41]:
KT4['platform'].unique()

array(['mobile', None, 'web'], dtype=object)

In [42]:
pd.value_counts(KT4['platform'], dropna=False)

mobile    93181238
web       38231988
NaN          28312
Name: platform, dtype: int64

## ITEM ID COLUMN

In [43]:
KT2['item_id'].unique()

array(['b3544', 'q5012', 'b3238', ..., 'q50', 'b3639', 'q5107'],
      dtype=object)

In [44]:
pd.value_counts(KT2['item_id'], dropna=False)

b8314    69736
b8316    65856
b8302    65330
b8312    65104
b295     64698
         ...  
b50          2
q8159        1
q8664        1
q5107        1
q50          1
Name: item_id, Length: 20031, dtype: int64

In [45]:
KT3['item_id'].unique()

array(['b3544', 'q5012', 'b3238', ..., 'b3639', 'q5107', 'e3639'],
      dtype=object)

In [46]:
pd.value_counts(KT3['item_id'], dropna=False)

e8314    71770
b8314    69736
e8316    67754
e8312    66514
e8302    66342
         ...  
e5630        2
q5107        1
q8159        1
q50          1
q8664        1
Name: item_id, Length: 29498, dtype: int64

In [47]:
KT4['item_id'].unique()

array(['b3544', 'q5012', 'b3238', ..., 'q5107', 'e3639', 'c6'],
      dtype=object)

In [48]:
pd.value_counts(KT4['item_id'], dropna=False)

b8314    269120
b1316    225369
b8316    218210
b8302    201593
b8312    191757
          ...  
p83           1
c50           1
q50           1
c22           1
q5107         1
Name: item_id, Length: 29642, dtype: int64

## ACTION TYPE COLUMN

In [49]:
KT2['action_type'].unique()

array(['enter', 'respond', 'submit'], dtype=object)

In [50]:
pd.value_counts(KT2['action_type'], dropna=False)

respond    23384480
submit     16488061
enter      16488061
Name: action_type, dtype: int64

In [51]:
KT3['action_type'].unique()

array(['enter', 'respond', 'submit', 'quit'], dtype=object)

In [52]:
pd.value_counts(KT3['action_type'], dropna=False)

enter      32943087
respond    23384480
submit     16488061
quit       16455026
Name: action_type, dtype: int64

In [53]:
KT4['action_type'].unique()

array(['enter', 'respond', 'submit', 'play_video', 'pause_video', 'quit',
       'play_audio', 'pause_audio', 'pay', 'erase_choice',
       'undo_erase_choice', 'refund', 'enroll_coupon'], dtype=object)

In [54]:
pd.value_counts(KT4['action_type'], dropna=False)

enter                32943087
respond              23384480
pause_audio          16879046
play_audio           16580464
submit               16488061
quit                 16455026
erase_choice          4714534
play_video            1928356
pause_video           1898080
undo_erase_choice      142092
pay                     26583
refund                   1126
enroll_coupon             603
Name: action_type, dtype: int64

## SOURCE COLUMN

In [55]:
KT2['source'].unique()

array(['diagnosis', 'sprint', 'review_quiz', 'adaptive_offer', 'tutor',
       'my_note', 'review'], dtype=object)

In [56]:
pd.value_counts(KT2['source'], dropna=False)

sprint            40018192
diagnosis          6623563
my_note            3901232
adaptive_offer     2726362
review_quiz        2235537
tutor               480846
review              374870
Name: source, dtype: int64

In [57]:
KT3['source'].unique()

array(['diagnosis', 'archive', 'sprint', 'review', 'my_note',
       'review_quiz', 'adaptive_offer', 'tutor'], dtype=object)

In [58]:
pd.value_counts(KT3['source'], dropna=False)

sprint            64679400
my_note            7033452
diagnosis          6623615
adaptive_offer     5124058
review_quiz        3625193
review              806584
tutor               723128
archive             655224
Name: source, dtype: int64

In [59]:
KT4['source'].unique()

array(['diagnosis', 'archive', 'sprint', 'review', 'my_note',
       'review_quiz', 'adaptive_offer', None, 'tutor'], dtype=object)

In [60]:
pd.value_counts(KT4['source'], dropna=False)

sprint            93699620
my_note           10874843
adaptive_offer     8684878
diagnosis          7823171
review_quiz        4947945
archive            2756068
review             1427814
tutor              1198887
NaN                  28312
Name: source, dtype: int64

## REMAINING UNCOMMON COLUMNS OF KT1 

In [61]:
KT1['solving_id'].unique()

array([    1,     2,     3, ..., 33130, 33131, 33132], dtype=int64)

In [62]:
pd.value_counts(KT1['solving_id'], dropna=False)

5        1026947
6         936479
7         891635
15        807938
16        802683
          ...   
32646          1
32645          1
32644          1
32643          1
33132          1
Name: solving_id, Length: 33132, dtype: int64

In [63]:
KT1['question_id'].unique()

array(['q5012', 'q4706', 'q4366', ..., 'q10342', 'q10343', 'q10552'],
      dtype=object)

In [64]:
pd.value_counts(KT1['question_id'], dropna=False)

q176      241688
q8074     240540
q8098     239502
q6185     215507
q1279     209663
           ...  
q10341         1
q9244          1
q1490          1
q10343         1
q10340         1
Name: question_id, Length: 12284, dtype: int64

In [65]:
KT1['elapsed_time'].unique()

array([   38000,    24000,    68000, ...,  3541000,  3850000, 65672000],
      dtype=int64)

In [66]:
pd.value_counts(KT1['elapsed_time'], dropna=False)

17000      4698657
16000      4349897
18000      4265367
19000      3690281
15000      3376073
            ...   
1468000          1
2974000          1
9233000          1
7564000          1
7926000          1
Name: elapsed_time, Length: 9298, dtype: int64

## REMAINING UNCOMMON COLUMNS OF KT4

In [67]:
KT4['cursor_time'].unique()

array([    nan,      0.,   4805., ..., 349044., 349545., 351570.])

In [68]:
pd.value_counts(KT4['cursor_time'], dropna=False)

NaN         94155592
0.0         10927043
4100.0        101048
3865.0         92997
1045.0         72796
              ...   
282787.0           1
312403.0           1
360782.0           1
238426.0           1
271718.0           1
Name: cursor_time, Length: 386168, dtype: int64

# NOW WE ANALYZE THE EDNET CONTENT CSV FILES

In [70]:
coupons.columns

Index(['coupon_id', 'coupon_type', 'duration'], dtype='object')

In [71]:
lectures.columns

Index(['lecture_id', 'part', 'tags', 'video_length', 'deployed_at'], dtype='object')

In [72]:
questions.columns

Index(['question_id', 'bundle_id', 'explanation_id', 'correct_answer', 'part',
       'tags', 'deployed_at'],
      dtype='object')

In [ ]:
payments.columns

## CHECKING WHICH USERS ARE MISSSING FROM EACH DATASET

### KT1 DATA SET

In [7]:
KT1_list = list(range(1, 784310))

In [8]:
missing_from_KT1 = (set(KT1_list)).difference(set(KT1['user_iD']))

In [9]:
sorted(missing_from_KT1)

[27,
 38,
 40,
 43,
 45,
 209,
 499,
 603,
 1176,
 1645,
 1736,
 1770,
 1892,
 1911,
 2578,
 2597,
 4223,
 4933,
 5294,
 6226,
 6247,
 6248,
 6249,
 6278,
 6279,
 6627,
 6672,
 6780,
 6781,
 6949,
 7304,
 7307,
 7328,
 7375,
 7415,
 7427,
 7430,
 7698,
 7751,
 7766,
 7780,
 7816,
 7848,
 7898,
 7951,
 7975,
 8038,
 8063,
 8085,
 8127,
 8140,
 8142,
 8166,
 8172,
 8184,
 8193,
 8261,
 8263,
 8269,
 8275,
 8282,
 8299,
 8327,
 8343,
 8372,
 8390,
 8407,
 8427,
 8476,
 8481,
 8493,
 8556,
 8562,
 8565,
 8619,
 8655,
 8665,
 8670,
 8755,
 8760,
 8789,
 8813,
 8828,
 8840,
 8885,
 8888,
 8928,
 8932,
 8984,
 9001,
 9010,
 9057,
 9080,
 9117,
 9151,
 9213,
 9227,
 9231,
 9297,
 9306,
 9374,
 9392,
 9393,
 9478,
 9509,
 9530,
 9543,
 9630,
 9636,
 9640,
 9674,
 9685,
 9695,
 9698,
 9702,
 9703,
 9711,
 9712,
 9723,
 9727,
 9744,
 9765,
 9769,
 9798,
 9804,
 9878,
 9879,
 9891,
 9922,
 9929,
 9950,
 9965,
 9975,
 9984,
 10008,
 10016,
 10051,
 10053,
 10070,
 10078,
 10093,
 10100,
 10117,
 10

In [23]:
len(missing_from_KT1)

42210

In [31]:
KT1DataFiles = 784309

In [32]:
KT1DataFiles - len(missing_from_KT1)

742099

### KT2 DATA SET

In [10]:
KT2_list = list(range(1, 294445))


In [11]:
missing_from_KT2 = (set(KT2_list)).difference(set(KT2['user_iD']))

In [12]:
sorted(missing_from_KT2)

[2,
 17,
 18,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 57,
 58,
 63,
 92,
 95,
 96,
 109,
 110,
 129,
 135,
 157,
 158,
 165,
 176,
 179,
 186,
 187,
 201,
 207,
 208,
 209,
 215,
 216,
 219,
 220,
 238,
 249,
 257,
 263,
 268,
 282,
 285,
 317,
 320,
 324,
 328,
 340,
 343,
 348,
 354,
 358,
 366,
 373,
 395,
 415,
 416,
 419,
 425,
 432,
 447,
 450,
 466,
 477,
 478,
 489,
 499,
 501,
 506,
 514,
 526,
 535,
 539,
 545,
 551,
 554,
 561,
 577,
 580,
 588,
 591,
 592,
 594,
 600,
 603,
 614,
 630,
 640,
 641,
 647,
 678,
 698,
 705,
 706,
 710,
 719,
 726,
 729,
 731,
 741,
 742,
 744,
 747,
 753,
 755,
 767,
 784,
 792,
 793,
 795,
 799,
 809,
 817,
 831,
 833,
 834,
 837,
 847,
 881,
 887,
 891,
 895,
 903,
 911,
 932,
 944,
 955,
 956,
 960,
 969,
 971,
 975,
 977,
 979,
 987,
 994,
 1004,
 1023,
 1025,
 1029,
 1041,
 1066,
 1071,
 1072,
 1093,
 1122,
 1125,
 1141,
 1143,
 1153,
 1168,
 1176,
 1201,
 1205,
 

In [25]:
len(missing_from_KT2)

257865

In [33]:
KT2DataFiles = 297444

In [34]:
KT2DataFiles - len(missing_from_KT2)

39579

## KT3 DATA SET

In [13]:
KT3_list = list(range(1, 297916))

In [14]:
missing_from_KT3 = (set(KT3_list)).difference(set(KT3['user_iD']))

In [15]:
sorted(missing_from_KT3)

[2,
 17,
 18,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 57,
 58,
 63,
 92,
 95,
 96,
 109,
 110,
 129,
 135,
 157,
 158,
 165,
 176,
 179,
 186,
 187,
 201,
 207,
 208,
 209,
 215,
 216,
 219,
 220,
 238,
 249,
 257,
 263,
 268,
 282,
 285,
 317,
 320,
 324,
 328,
 340,
 343,
 348,
 354,
 358,
 366,
 373,
 395,
 415,
 416,
 419,
 425,
 432,
 447,
 450,
 466,
 477,
 478,
 489,
 499,
 501,
 506,
 514,
 526,
 535,
 539,
 545,
 551,
 554,
 561,
 577,
 580,
 588,
 591,
 592,
 594,
 600,
 603,
 614,
 630,
 640,
 641,
 647,
 678,
 698,
 705,
 706,
 710,
 719,
 726,
 729,
 731,
 741,
 742,
 744,
 747,
 753,
 755,
 767,
 784,
 792,
 793,
 795,
 799,
 809,
 817,
 831,
 833,
 834,
 837,
 847,
 881,
 887,
 891,
 895,
 903,
 911,
 932,
 944,
 955,
 956,
 960,
 969,
 971,
 975,
 977,
 979,
 987,
 994,
 1004,
 1023,
 1025,
 1041,
 1066,
 1071,
 1072,
 1093,
 1122,
 1125,
 1141,
 1143,
 1153,
 1176,
 1201,
 1205,
 1206,
 1211,
 

In [26]:
len(missing_from_KT3)

258893

In [35]:
KT3DataFiles = 297915

In [36]:
KT3DataFiles - len(missing_from_KT3)

39022

## KT4 DATA SET

In [16]:
KT4_list = list(range(1, 297916))

In [17]:
missing_from_KT4 = (set(KT4_list)).difference(set(KT4['user_iD']))

In [18]:
sorted(missing_from_KT4)

[2,
 17,
 18,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 57,
 58,
 63,
 92,
 95,
 96,
 109,
 110,
 129,
 135,
 157,
 158,
 165,
 176,
 179,
 186,
 187,
 201,
 207,
 208,
 209,
 215,
 216,
 219,
 220,
 238,
 249,
 257,
 263,
 268,
 282,
 285,
 317,
 320,
 324,
 328,
 340,
 343,
 348,
 354,
 358,
 366,
 373,
 395,
 415,
 416,
 419,
 425,
 432,
 447,
 450,
 466,
 477,
 478,
 489,
 499,
 501,
 506,
 514,
 526,
 535,
 539,
 545,
 551,
 554,
 561,
 577,
 580,
 588,
 591,
 592,
 594,
 600,
 603,
 614,
 630,
 640,
 641,
 647,
 678,
 698,
 705,
 706,
 710,
 719,
 726,
 729,
 731,
 741,
 742,
 744,
 747,
 753,
 755,
 767,
 784,
 792,
 793,
 795,
 799,
 809,
 817,
 831,
 833,
 834,
 837,
 847,
 881,
 887,
 891,
 895,
 903,
 911,
 932,
 944,
 955,
 956,
 960,
 969,
 971,
 975,
 977,
 979,
 987,
 994,
 1004,
 1023,
 1025,
 1041,
 1066,
 1071,
 1072,
 1093,
 1122,
 1125,
 1141,
 1143,
 1153,
 1176,
 1201,
 1205,
 1206,
 1211,
 

In [27]:
len(missing_from_KT4)

258893

In [37]:
KT4DataFiles = 297915

In [38]:
KT4DataFiles - len(missing_from_KT4)

39022

In [19]:
def common_member(a, b , c , d):
    a_set = set(missing_from_KT1) 
    b_set = set(missing_from_KT2)
    c_set = set(missing_from_KT3)
    d_set = set(missing_from_KT4)
      
    # check length 
    ABC = (a_set.intersection(b_set).intersection(c_set).intersection(d_set))
    if len(ABC) > 0:
        return(ABC)
    else:
        return("no common elements") 
    
    
a = missing_from_KT1 
b = missing_from_KT2
c = missing_from_KT3
d = missing_from_KT4




Common_Users = common_member(a, b, c, d)

sorted(Common_Users)



[27,
 38,
 40,
 43,
 45,
 209,
 499,
 603,
 1176,
 1736,
 1770,
 1892,
 1911,
 2578,
 2597,
 4223,
 4933,
 5294,
 6226,
 6247,
 6248,
 6249,
 6278,
 6279,
 6627,
 6672,
 6780,
 6781,
 6949,
 7304,
 7307,
 7328,
 7375,
 7415,
 7427,
 7430,
 7698,
 7751,
 7766,
 7780,
 7816,
 7848,
 7898,
 7951,
 7975,
 8038,
 8063,
 8085,
 8127,
 8140,
 8142,
 8166,
 8172,
 8184,
 8193,
 8261,
 8263,
 8269,
 8275,
 8282,
 8299,
 8327,
 8343,
 8372,
 8390,
 8427,
 8476,
 8481,
 8493,
 8556,
 8562,
 8565,
 8619,
 8655,
 8665,
 8670,
 8755,
 8789,
 8813,
 8828,
 8840,
 8885,
 8888,
 8928,
 8932,
 8984,
 9001,
 9057,
 9080,
 9117,
 9151,
 9213,
 9227,
 9231,
 9297,
 9306,
 9374,
 9392,
 9393,
 9478,
 9530,
 9543,
 9630,
 9640,
 9674,
 9685,
 9695,
 9698,
 9702,
 9703,
 9711,
 9712,
 9723,
 9727,
 9744,
 9765,
 9769,
 9798,
 9878,
 9879,
 9891,
 9922,
 9929,
 9950,
 9965,
 9975,
 9984,
 10008,
 10016,
 10051,
 10053,
 10070,
 10078,
 10093,
 10100,
 10117,
 10135,
 10168,
 10173,
 10202,
 10212,
 10227,
 103

In [22]:
len(Common_Users)

1184

In [30]:
print(str(Common_Users))

{43008, 8193, 43010, 55296, 43013, 12294, 165904, 143377, 14355, 55319, 40986, 27, 16411, 258076, 153629, 53278, 122912, 104482, 43044, 81957, 38, 40, 14376, 278569, 43, 262188, 45, 20521, 20522, 16432, 20523, 20524, 20525, 18484, 12341, 18486, 20527, 20528, 20529, 41013, 41015, 12348, 41018, 16446, 43063, 10304, 12352, 155713, 43066, 43067, 8261, 264262, 8263, 43071, 10313, 43082, 190531, 122944, 8269, 14414, 14416, 6226, 8275, 12371, 18518, 20566, 110679, 96345, 8282, 20571, 20572, 12381, 20573, 18527, 20574, 20576, 16482, 20577, 18532, 20578, 20579, 6247, 6248, 6249, 18536, 8299, 12395, 143469, 18540, 20590, 10353, 14449, 20599, 20602, 123004, 18557, 4223, 6278, 6279, 12424, 8327, 10377, 20620, 14480, 10385, 143505, 10387, 20630, 8343, 20631, 20634, 49308, 20641, 10406, 12455, 77992, 282790, 20648, 20649, 20650, 131244, 20651, 20652, 20654, 20656, 161962, 14514, 161963, 8372, 51378, 16571, 10429, 12478, 24765, 41150, 69824, 14530, 41154, 14532, 41157, 8390, 41158, 14536, 18633, 4116